parameters:
#    produto.example.class: Intrix\ProdutoBundle\Example

services:
#    produto.example:
#        class: %produto.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
