parameters:
#    profissional.example.class: Intrix\ProfissionalBundle\Example

services:
#    profissional.example:
#        class: %profissional.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
