parameters:
#    estoque.example.class: Intrix\EstoqueBundle\Example

services:
#    estoque.example:
#        class: %estoque.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
